name: Releases

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: nightly-x86_64-pc-windows-gnu
      - name: build
        shell: powershell
        run: |
          # $env:RUSTFLAGS="-C target-feature=+crt-static"
          cargo build --target x86_64-pc-windows-gnu --release

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: rust-static
          path: ./target/*/release/rust-static.exe
